<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="erreur 404">
    <meta name="author" content="">

    <title>Page erreur 404</title>
    <link href="vues/css/bootstrap.min.css" rel="stylesheet">
    <link href="vues/css/blog-home.css" rel="stylesheet">
</head>
<body>
	<div class="container">
    <img src="vues/img/404.jpg" class="img-responsive " alt="Responsive image">
    </div>
</body>
</html>