<?php include "vues/globals/header.phtml";?>
<div class="container">

  <form class="form-signin" method="POST" novalidate>
    <h2 class="form-signin-heading">Créer un compte</h2>
    <label for="inputEmail" class="sr-only">Prenom</label>
    <input type="text" name="fname" id="inputFname" class="form-control"placeholder="Prenom" required autofocus>
    <label for="inputEmail" class="sr-only">Nom</label>
    <input type="text" name="lname" id="inputLname" class="form-control"placeholder="Nom" required>
    <label for="inputEmail" class="sr-only">Adresse Email</label>
    <input type="email" name="email" id="inputEmail" class="form-control"placeholder="Email address" required>
    <label for="inputPassword" class="sr-only">Mot de passe</label>
    <input type="password" name="mdp" id="inputPassword" class="form-control" placeholder="Password" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Créer un compte</button>
  </form>
</div> <!-- /container -->

<?php include "vues/globals/footer.phtml";?> 