<!DOCTYPE html>
<html lang="fr">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Loc'karting</title>

    <link rel="stylesheet" href="<?=ROOT;?>vues/lib/jquery.raty.css">

    <!-- Bootstrap Core CSS -->
    <link href="../css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../css/agency.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <link href="../css/full-slider.css" rel="stylesheet">

    <!-- mailchimp -->
    <link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">

    <!-- script shareaholic ds chaque page! -->
    <script type="text/javascript">
    //<![CDATA[
      (function() {
        var shr = document.createElement('script');
        shr.setAttribute('data-cfasync', 'false');
        shr.src = '//dsms0mj1bbhn4.cloudfront.net/assets/pub/shareaholic.js';
        shr.type = 'text/javascript'; shr.async = 'true';
        shr.onload = shr.onreadystatechange = function() {
          var rs = this.readyState;
          if (rs && rs != 'complete' && rs != 'loaded') return;
          var site_id = 'edd7c50d40812a89619b7ed435fc5432';
          try { Shareaholic.init(site_id); } catch (e) {}
        };
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(shr, s);
      })();
    //]]>
    </script>



</head>

<body id="page-top" class="index">

    <!-- Script pour google analytics a inclure ds chaque page!!-->
    <?php include_once("analyticstracking.php") ?>

    <!-- Navigation -->
    <nav class="navbar  navbar-inverse navbar-fixed-top" role="navigation" style="margin-bottom: 0px;
    height: 51px;">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <h1 style=" padding-left: 10px; width: 170px;height: 50px; margin-top: 10px; color: #feD136; float: left;">LE BLOG</h1>
                <button    style=" border-color: #fed136;
    background-color: #fed136;"type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="index.php"><img style="width: 100px; float:left" src="../img/logo.png"></a>
                
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a style="color:#fed136" href="../">Retour au site</a>
                    </li>
                    <li>
                        <a href="#" style="color:#fed136" class="dropdown-toggle" data-toggle="dropdown">Suivez-nous ! <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a style="color:#fed136" target="_blank" href="http://www.facebook.com/lockarting"> <i class="fa fa-facebook-square"></i> Facebook</a>
                                <a style="color:#fed136" target="_blank" href="https://plus.google.com/109144128606618517906/posts"> <i class="fa fa-google-plus-square"></i> Google+</a>
                                <a style="color:#fed136" target="_blank" href="https://fr.linkedin.com/pub/jean-marie-caizergues/64/754/321"> <i class="fa fa-linkedin-square"></i> Linkedin</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>        
        </div>
    </nav>